FROM python:3.12.5-alpine3.19

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY envs/ envs/
COPY src/ src/

ENV PYTHONPATH="$PYTHONPATH:/app"

CMD ["python", "src/scheduler/post_scheduler.py"]
