[mypy]
plugins = sqlalchemy.ext.mypy.plugin

[mypy-src.http_schemas.*]
disable_error_code = assignment

[mypy-src.logger.app_logger]
disable_error_code = misc

[mypy-tests.*]
disable_error_code = call-arg