"""Initial revision

Revision ID: 755ebfbcc1e8
Revises: 
Create Date: 2025-04-27 17:25:49.458821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '755ebfbcc1e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'USER', 'AUTHOR', name='role'), nullable=False),
    sa.Column('password', sa.String(), nullable=True, comment='Пароль'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('id', name=op.f('uq_app_user_id')),
    sa.UniqueConstraint('login', name=op.f('uq_app_user_login')),
    sa.UniqueConstraint('uuid', name=op.f('uq_app_user_uuid'))
    )
    op.create_table('tag',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag')),
    sa.UniqueConstraint('id', name=op.f('uq_tag_id')),
    sa.UniqueConstraint('name', name=op.f('uq_tag_name')),
    sa.UniqueConstraint('uuid', name=op.f('uq_tag_uuid'))
    )
    op.create_table('post',
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED', name='status'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False, comment='Количество просмотров от зарегистрированных пользователей, обновляется автоматически scheduler-ом '),
    sa.Column('to_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['app_user.id'], name=op.f('fk_post_author_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post')),
    sa.UniqueConstraint('id', name=op.f('uq_post_id')),
    sa.UniqueConstraint('uuid', name=op.f('uq_post_uuid'))
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_moderated', sa.Boolean(), nullable=False),
    sa.Column('content', sa.String(length=512), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['app_user.id'], name=op.f('fk_comment_author_id_app_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], name=op.f('fk_comment_parent_id_comment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_comment_post_id_post'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment')),
    sa.UniqueConstraint('id', name=op.f('uq_comment_id')),
    sa.UniqueConstraint('uuid', name=op.f('uq_comment_uuid'))
    )
    op.create_table('post_tag',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_post_tag_post_id_post'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_post_tag_tag_id_tag'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_tag')),
    sa.UniqueConstraint('id', name=op.f('uq_post_tag_id')),
    sa.UniqueConstraint('post_id', 'tag_id', name='unique_post_tag'),
    sa.UniqueConstraint('uuid', name=op.f('uq_post_tag_uuid'))
    )
    op.create_table('user_post_view',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_user_post_view_post_id_post'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_user_post_view_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_post_view')),
    sa.UniqueConstraint('id', name=op.f('uq_user_post_view_id')),
    sa.UniqueConstraint('user_id', 'post_id', name='unique_user_post_view'),
    sa.UniqueConstraint('uuid', name=op.f('uq_user_post_view_uuid'))
    )
    op.create_table('comment_reaction',
    sa.Column('reaction_type', sa.Unicode(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name=op.f('fk_comment_reaction_comment_id_comment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_comment_reaction_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment_reaction')),
    sa.UniqueConstraint('id', name=op.f('uq_comment_reaction_id')),
    sa.UniqueConstraint('user_id', 'comment_id', name='unique_comment_reaction'),
    sa.UniqueConstraint('uuid', name=op.f('uq_comment_reaction_uuid'))
    )
    # ### end Alembic commands ###

    # post
    op.create_index('ix_post_status', 'post', ['status'])
    op.create_index('ix_post_author_id', 'post', ['author_id'])
    op.create_index('ix_post_category', 'post', ['category'])
    op.create_index('ix_post_created_at', 'post', ['created_at'])
    op.execute(
        "CREATE INDEX ix_post_content_fulltext ON post USING GIN (to_tsvector('russian', content))"
    )
    op.execute(
        "CREATE INDEX ix_post_title_fulltext ON post USING GIN (to_tsvector('russian', title))"
    )

    # comment
    op.create_index('ix_comment_post_id', 'comment', ['post_id'])
    op.create_index('ix_comment_author_id', 'comment', ['author_id'])
    op.create_index('ix_comment_parent_id', 'comment', ['parent_id'])
    op.create_index('ix_comment_is_moderated', 'comment', ['is_moderated'])
    op.create_index('ix_comment_created_at', 'comment', ['created_at'])

    # post_tag
    op.create_index('ix_post_tag_post_id', 'post_tag', ['post_id'])
    op.create_index('ix_post_tag_tag_id', 'post_tag', ['tag_id'])

    # user_post_view
    op.create_index('ix_user_post_view_user_id', 'user_post_view', ['user_id'])
    op.create_index('ix_user_post_view_post_id', 'user_post_view', ['post_id'])
    op.create_index('ix_user_post_view_created_at', 'user_post_view', ['created_at'])

    # comment_reaction
    op.create_index('ix_comment_reaction_user_id', 'comment_reaction', ['user_id'])
    op.create_index('ix_comment_reaction_comment_id', 'comment_reaction', ['comment_id'])

    # === Тестовые данные ===
    # Пароль для всех пользователей (argon2id hash)
    # password: password
    password_hash = "$argon2id$v=19$m=65536,t=3,p=4$ncMSqI2xTIDvvE5bc2QxMDQEXhCS8rC3E+kjReYcuoDT8bdS2wXQU/9AZ6UVa31knwBp2pW2zcYnIVIw22jjcw$kWOLjCbAuUZT4bNDE7TKL+bKiARhoNz7kIJXmmlfpP7CfJYTUWxf7TFcD1S21QGvVd1iZ0k4dOPq4LGdIYnB5A"
    now = sa.func.now()
    op.execute("""
        INSERT INTO app_user (id, login, role, password, uuid, created_at)
        VALUES
            (1, 'admin@yandex.ru', 'ADMIN', '{pw}', gen_random_uuid(), now()),
            (2, 'user1@yandex.ru', 'USER', '{pw}', gen_random_uuid(), now()),
            (3, 'author@yandex.ru', 'AUTHOR', '{pw}', gen_random_uuid(), now()),
            (4, 'user2@yandex.ru', 'USER', '{pw}', gen_random_uuid(), now())
    """.format(pw=password_hash))

    op.execute("""
        INSERT INTO tag (id, name, uuid, created_at) VALUES
            (1, 'python', gen_random_uuid(), now()),
            (2, 'fastapi', gen_random_uuid(), now()),
            (3, 'postgresql', gen_random_uuid(), now())
    """)

    op.execute("""
        INSERT INTO post (id, title, content, category, status, author_id, views, created_at, uuid)
        VALUES
            (1, 'Первый пост', 'Текст первого поста', 'dev', 'PUBLISHED', 3, 1, now(), gen_random_uuid()),
            (2, 'Второй пост', 'Текст второго поста', 'news', 'DRAFT', 3, 1, now(), gen_random_uuid()),
            (3, 'Третий пост', 'Текст третьего поста', 'dev', 'PUBLISHED', 2, 1, now(), gen_random_uuid())
    """)

    op.execute("""
        INSERT INTO comment (id, post_id, author_id, parent_id, content, is_moderated, created_at, uuid)
        VALUES
            (1, 1, 2, NULL, 'Отличный пост!', true, now(), gen_random_uuid()),
            (2, 1, 1, 1, 'Спасибо за информацию.', false, now(), gen_random_uuid()),
            (3, 2, 4, NULL, 'Жду продолжения!', true, now(), gen_random_uuid()),
            (4, 1, 3, 2, 'Согласен с предыдущим комментарием!', true, now(), gen_random_uuid()),
            (5, 1, 4, 2, 'А мне кажется, можно было бы подробнее раскрыть тему.', true, now(), gen_random_uuid()),
            (6, 2, 1, 3, 'Поддерживаю, жду продолжения!', true, now(), gen_random_uuid()),
            (7, 2, 2, 6, 'Интересно, когда выйдет следующий пост?', true, now(), gen_random_uuid()),
            (8, 3, 3, NULL, 'Спасибо за полезную информацию!', true, now(), gen_random_uuid()),
            (9, 3, 4, 8, 'Очень полезный пост!', false, now(), gen_random_uuid()),
            (10, 3, 1, 8, 'Можно ли подробнее про примеры?', true, now(), gen_random_uuid()),
            (11, 1, 2, 5, 'Ответ на комментарий 5', true, now(), gen_random_uuid()),
            (12, 1, 1, 11, 'Ответ на комментарий 11', true, now(), gen_random_uuid()),
            (13, 1, 3, 12, 'Ответ на комментарий 12', true, now(), gen_random_uuid()),
            (14, 1, 4, 13, 'Ответ на комментарий 13', true, now(), gen_random_uuid()),
            (15, 2, 1, 7, 'Ответ на комментарий 7', true, now(), gen_random_uuid()),
            (16, 2, 2, 15, 'Ответ на комментарий 15', true, now(), gen_random_uuid()),
            (17, 2, 3, 16, 'Ответ на комментарий 16', true, now(), gen_random_uuid()),
            (18, 2, 4, 17, 'Ответ на комментарий 17', true, now(), gen_random_uuid()),
            (19, 3, 1, 10, 'Ответ на комментарий 10', true, now(), gen_random_uuid()),
            (20, 3, 2, 19, 'Ответ на комментарий 19', true, now(), gen_random_uuid()),
            (21, 3, 3, 20, 'Ответ на комментарий 20', true, now(), gen_random_uuid()),
            (22, 3, 4, 21, 'Ответ на комментарий 21', true, now(), gen_random_uuid()),
            (23, 1, 1, 14, 'Глубокий уровень вложенности 1', true, now(), gen_random_uuid()),
            (24, 1, 2, 23, 'Глубокий уровень вложенности 2', true, now(), gen_random_uuid()),
            (25, 1, 3, 24, 'Глубокий уровень вложенности 3', true, now(), gen_random_uuid()),
            (26, 1, 4, 25, 'Глубокий уровень вложенности 4', true, now(), gen_random_uuid()),
            (27, 1, 1, 26, 'Глубокий уровень вложенности 5', true, now(), gen_random_uuid()),
            (28, 1, 2, 27, 'Глубокий уровень вложенности 6', true, now(), gen_random_uuid()),
            (29, 1, 3, 28, 'Глубокий уровень вложенности 7', true, now(), gen_random_uuid()),
            (30, 1, 4, 29, 'Глубокий уровень вложенности 8', true, now(), gen_random_uuid())
    """)
    op.execute("SELECT setval(pg_get_serial_sequence('comment', 'id'), 30, true)")

    op.execute("""
        INSERT INTO comment_reaction (id, reaction_type, user_id, comment_id, uuid, created_at)
        VALUES
            (1, '❤️', 1, 1, gen_random_uuid(), now()),
            (2, '❤️', 2, 2, gen_random_uuid(), now()),
            (3, '👍', 3, 1, gen_random_uuid(), now()),
            (4, '😂', 4, 1, gen_random_uuid(), now()),
            (5, '🎉', 2, 4, gen_random_uuid(), now()),
            (6, '😡', 1, 5, gen_random_uuid(), now()),
            (7, '👍', 4, 6, gen_random_uuid(), now()),
            (8, '👎', 3, 7, gen_random_uuid(), now()),
            (9, '😂', 1, 8, gen_random_uuid(), now()),
            (10, '🎉', 2, 9, gen_random_uuid(), now()),
            (11, '❤️', 3, 10, gen_random_uuid(), now())
    """)

    op.execute("""
        INSERT INTO post_tag (id, post_id, tag_id, uuid, created_at)
        VALUES
            (1, 1, 1, gen_random_uuid(), now()),
            (2, 1, 2, gen_random_uuid(), now()),
            (3, 2, 3, gen_random_uuid(), now())
    """)

    op.execute("""
        INSERT INTO user_post_view (id, user_id, post_id, uuid, created_at)
        VALUES
            (1, 2, 1, gen_random_uuid(), now()),
            (2, 4, 2, gen_random_uuid(), now())
    """)

    # Корректировка последовательностей id
    op.execute("SELECT setval(pg_get_serial_sequence('app_user', 'id'), 4, true)")
    op.execute("SELECT setval(pg_get_serial_sequence('tag', 'id'), 3, true)")
    op.execute("SELECT setval(pg_get_serial_sequence('post', 'id'), 3, true)")
    op.execute("SELECT setval(pg_get_serial_sequence('comment', 'id'), 30, true)")
    op.execute("SELECT setval(pg_get_serial_sequence('post_tag', 'id'), 3, true)")
    op.execute("SELECT setval(pg_get_serial_sequence('user_post_view', 'id'), 2, true)")
    op.execute("SELECT setval(pg_get_serial_sequence('comment_reaction', 'id'), 11, true)")


def downgrade() -> None:
    # Удаление индексов для post
    op.drop_index('ix_post_status', table_name='post')
    op.drop_index('ix_post_author_id', table_name='post')
    op.drop_index('ix_post_category', table_name='post')
    op.drop_index('ix_post_created_at', table_name='post')
    op.execute("DROP INDEX IF EXISTS ix_post_title_fulltext")
    op.execute("DROP INDEX IF EXISTS ix_post_content_fulltext")

    # Удаление индексов для comment
    op.drop_index('ix_comment_post_id', table_name='comment')
    op.drop_index('ix_comment_author_id', table_name='comment')
    op.drop_index('ix_comment_parent_id', table_name='comment')
    op.drop_index('ix_comment_is_moderated', table_name='comment')
    op.drop_index('ix_comment_created_at', table_name='comment')

    # Удаление индексов для post_tag
    op.drop_index('ix_post_tag_post_id', table_name='post_tag')
    op.drop_index('ix_post_tag_tag_id', table_name='post_tag')

    # Удаление индексов для user_post_view
    op.drop_index('ix_user_post_view_user_id', table_name='user_post_view')
    op.drop_index('ix_user_post_view_post_id', table_name='user_post_view')
    op.drop_index('ix_user_post_view_created_at', table_name='user_post_view')

    # Удаление индексов для comment_reaction
    op.drop_index('ix_comment_reaction_user_id', table_name='comment_reaction')
    op.drop_index('ix_comment_reaction_comment_id', table_name='comment_reaction')

    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_reaction')
    op.drop_table('user_post_view')
    op.drop_table('post_tag')
    op.drop_table('comment')
    op.drop_table('post')
    op.drop_table('tag')
    op.drop_table('app_user')
    # ### end Alembic commands ###

    # Удаление типов ENUM
    op.execute('DROP TYPE IF EXISTS status')
    op.execute('DROP TYPE IF EXISTS role')
